name: Setup SF CLI
description: Action provides simple and super fast way to install and cache Salesforce CLI
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: Version of CLI to be installed
    required: false
    default: 'latest'
runs:

  using: composite
  steps:
    - name: Restore CLI from cache
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: /usr/local/bin/sf/**
        key: sf-cli-${{ inputs.version }}

    - name: Install CLI
      shell: bash
      id: install-cli
      env:
        CLI_VERSION: ${{ inputs.version }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install @salesforce/cli@$CLI_VERSION --global
        echo "path=$(which sf)" >> $GITHUB_OUTPUT
        echo "version=$(sf --version | grep -o '^\S*')" >> $GITHUB_OUTPUT

    - uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.install-cli.outputs.path }}
        key: sf-cli-${{steps.install-cli.outputs.version}}

    - uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.install-cli.outputs.path }}
        key: sf-cli-${{inputs.version}}


    - shell: bash
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        echo "/usr/local/bin/sf" >> $GITHUB_PATH
