name: Setup SF CLI
description: Action provides simple and super fast way to install and cache Salesforce CLI
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: Version of CLI to be installed
    required: false
    default: 'latest'
runs:

  using: composite
  steps:
    - name: Cache CLI
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/sf
        key: sf-cli-${{ inputs.version }}

    - name: Install CLI
      shell: bash
      id: install-cli
      env:
        CLI_VERSION: ${{ inputs.version }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --prefix ~/sf @salesforce/cli@$CLI_VERSION --global

    - shell: bash
      run: echo "~/sf/bin" >> $GITHUB_PATH

    - shell: bash
      run: sf --version

