name: Setup SF CLI
description: Action provides simple and super fast way to instal and cache Salesforce CLI
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: Version of CLI to be installed
    required: false
    default: 'latest'
runs:

  using: composite
  steps:
    - name: Cache CLI
      uses: actions/cache/restore@v4
      id: cache
      env:
        CLI_VERSION: ${{ inputs.version }}
      with:
        path: /usr/local/bin/sf/**
        key: cli-cache-$CLI_VERSION

    - name: Install CLI
      shell: bash
      id: install-cli
      env:
        CLI_VERSION: ${{ inputs.version }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install @salesforce/cli@$CLI_VERSION --global
        echo "path=$(which sf)" >> $GITHUB_OUTPUT
        echo "version=$(sf --version)" >> $GITHUB_OUTPUT

    - uses: actions/cache/save@v4
      env:
        CLI_PATH: ${{ steps.install-cli.outputs.path }}
      with:
        path: $CLI_PATH
        key:
          - cli-cache-${{ steps.install-cli.outputs.version }}

    - uses: actions/cache/save@v4
      env:
        CLI_PATH: ${{ steps.install-cli.outputs.path }}
      with:
        path: $CLI_PATH
        key: cli-cache-${{ inputs.version }}


    - shell: bash
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        echo "/usr/local/bin/sf" >> $GITHUB_PATH
