name: Test Build
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        required: false
        description: Version of CLI to be installed
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test build
    runs-on: 'ubuntu-latest'
    steps:
      - run: gh cache delete --all
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./

      - name: Check installed CLI version
        run: sf --version

      - uses: ./
      - name: Check installed CLI version after restore from cache
        run: sf --version