name: Test
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        required: false
        description: Version of CLI to be installed
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./
        with:
          version: 'latest'

      - name: Check installed CLI version
        run: sf --version